# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ValidateGeodata
                                 A QGIS plugin
 Vaildate geodata in repect to geometry, coordinate reference system and data structure
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-16
        copyright            : (C) 2025 by Jo Ritter
        email                : tempmail@mail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ValidateGeodata class from file ValidateGeodata.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geodata_validation import ValidateGeodata
    return ValidateGeodata(iface)
